name = "Seb's Briefing Table"
prefix = "sebs_briefing_table"
author = "Seb"
template = "cba"
mainprefix = "z"
include = ["./include"]
files = [
    "example_mission"
] 
folder_optionals = true
sig_version = 3
